apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: customruns-reader
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch

